#!/bin/bash


######################### Configuration Section #######################

# Use following variables as global-scope
set -a

####################################################################
######################## Upstream Settings #########################
####################################################################
# Modify these envs if you are trying to develop forks             #
####################################################################

## Target GitHub Repository's raw baseURL for fetching scripts
[[ -z "$REPO_BASE_URL" ]] && REPO_BASE_URL="https://raw.githubusercontent.com/Alex4386/minecraft-server-launcher"

## Target branch.
[[ -z "$REPO_BASE_BRANCH" ]] && REPO_BRANCH="feature/one-liner-oobe-and-openj9-support"


if [[ -z $FORCE_USE_ENV ]]; then

####################################################################
########################## Configurations ##########################
####################################################################
# Configuration variables for minecraft-server-launcher            #
####################################################################

## Server directory name
DIR="server"

## Server type (local path or type[vanilla, spigot, paper]-version[1.xx.x, unspecified]-build[latest, unspecified, xx]-[dev])
SERVER="paper-1.19-latest"

## Server memory (GB)
MEMORY=4

## When the server shuts down, use tar to back up.
BACKUP=false

## The server will always restart.
RESTART=false


####################################################################
################## Spigot or Paper Configurations ##################
####################################################################
# Configuration variables for minecraft-server-launcher            #
####################################################################

## The maximum amount of players that the server will allow, this will bypass the max-players= value in server.properties file.
PLAYERS=100

## This parameter allows you to manually define the plugins directory to use for the server.
PLUGINS="plugins"

## This parameter will put all worlds your server uses into a specific directory, it's useful if you have many folders inside in the main server directory.
WORLDS="worlds"

## Server port, default value from server.properties (25565)
PORT=-1

## jdwp port, Enable debug mode when 0 or higher (5005)
DEBUG_PORT=-1

# Preinstallation plugins (url)
DEFAULT_PLUGINS=(
   'https://github.com/monun/auto-reloader/releases/download/0.0.5/auto-reloader-0.0.5.jar'
)

# Uncomment to enable OpenJ9 performance tuning for VMs
# VIRTUALIZED=true

fi

# Use following variables as local-scope
set +a

####################### End of Configuration ######################


# Download itself if it is running from stdout (installation phase) 
[[ -t 1 ]] || [[ -f run ]] && wget -q -c --content-disposition -P . -N "$REPO_BASE_URL/$REPO_BRANCH/run" > /dev/null && chmod +x run > /dev/null

# Setup target directory
mkdir -p "$DIR" && cd "$DIR" || exit

[[ -f ../startSetup ]] && cp ../startSetup .
[[ ! -f startSetup ]] && wget -q -c --content-disposition -P . -N "$REPO_BASE_URL/$REPO_BRANCH/deploy/startSetup" > /dev/null

chmod +x ./startSetup
./startSetup "${DEFAULT_PLUGINS[@]}"
