#!/bin/bash

# Testing with Fork
REPO_BASE_URL="https://raw.githubusercontent.com/Alex4386/minecraft-server-launcher"
REPO_BRANCH="master"

# Check wget
! type -p wget >/dev/null && echo "wget not found" && exit

# Check jq
! type -p jq >/dev/null && echo "jq not found" && exit

# Check java
! type -p java >/dev/null && echo "java not found" && exit

# Check local path
[[ -f $SERVER ]] && JAR=$SERVER

if [[ -z $JAR ]]; then
  [[ -f ../startDeploy ]] && cp ../startDeploy .
  [[ ! -f startDeploy ]] && wget -q -c --content-disposition -P . -N "$REPO_BASE_URL/$REPO_BRANCH/startDeploy"
  chmod +x ./startDeploy
  JAR=$(./startDeploy $SERVER)
fi

# Exit if jar not found
[[ ! -f $JAR ]] && echo "Jar not found for $SERVER - $JAR" && exit

export JAR

# Download plugins (Only if it's not vanilla)
if [[ $SERVER != vanilla* ]]; then
  dest="$PLUGINS"
  [[ -z $dest ]] && dest="./plugins"

  mkdir -p "$dest"
  for i in "$@"; do
    wget -q -c --content-disposition -P "$dest" -N "$i"
  done
fi

# Download start script
[[ -f ../start.sh ]] && cp ../start.sh .
[[ ! -f start.sh ]] && wget -q -c --content-disposition -P . -N "$REPO_BASE_URL/$REPO_BRANCH/start.sh" >/dev/null

# Start server
chmod +x ./start.sh
./start.sh launch
